### ISSUE TITLE
@vant/weapp 编译报错

### ISSUE THREAD

**Issue by xuyawen** [WeBankFinTech/wxa#126]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具]
  * Platform version: [stable 1.05.2103200]
  * Wechat version: [8.0.2]
  * @wxa/cli2 version: [2.2.18]
  * @wxa/core version: ["^2.2.5"]
  * other version: [@vant/weapp": "^1.6.8", "@wxa/redux": "^2.2.5" ]
  
## Reproduce
  引入 @vant/weapp": "^1.6.8" 后进行编译，出现报错
  
![微信截图_20210422120210](https://user-images.githubusercontent.com/39393061/115654444-ba712880-a363-11eb-87f7-da7575250858.png)

### Observed Results

  [实际表现]
   在反复切换es6转es5的时候会编译成功，控制台还是有大量报错，视图显示后在点编译依然是第一次编译时的报错
    ![微信截图_20210422120248](https://user-images.githubusercontent.com/39393061/115654601-0754ff00-a364-11eb-9c86-5ef33476d63d.png)
    第一次使用wxa，多多谅解
  
  
### Expected Results

  [期望表现]
  编译成功，无报错

**Comment by bestony** [comment]
参考这个试试看 ？https://github.com/WeBankFinTech/wxa/issues/89

**Comment by xuyawen** [comment]
> 参考这个试试看 ？#89

有试过 dev-feat-npm-resolve 分支重新编译 cli，build 后 dist目录 下也有对应的组件，还是有很多报错，这和开发者工具里的本地设置会有关系吗?

**Comment by Genuifx** [comment]
建议勾选 es6 转 es5 @xuyawen

**Comment by Genuifx** [comment]
使用最新发布的 `@wxa/cli2@2.3.0-rc.8` 试试？

**Comment by Genuifx** [comment]
实测 
```vue
<config>
{
    "navigationBarTitleText": "首页",
    "usingComponents": {
      "van-button": "@vant/weapp/button/index"
    }
}
</config>

<template>
<view class="page">
    <view class="animated pulse">
        hello, this is wxa!
    </view>
    <van-button class="btn" type="primary"> Van Button </van-button>
</view>
</template>
```

![image](https://user-images.githubusercontent.com/10156994/115712076-e95cbe00-a3a6-11eb-8042-cad35e5f4c1d.png)

**Comment by xuyawen** [comment]
> 使用最新发布的 `@wxa/cli2@2.3.0-rc.8` 试试？

嗯，可以了。ES6转ES5真的要勾选吗？会出现这个报错
![1111](https://user-images.githubusercontent.com/39393061/115826770-fb3d7000-a43d-11eb-9780-cb0e3e78ee41.png)

**Comment by Genuifx** [comment]
@xuyawen 这个报错是另外的问题，检查下你引入的regenerator-runtime的版本，微信小程序的话建议依赖 0.11-0.12
