### ISSUE TITLE
期望能从原生小程序代码，反向编译到wxa 这样老项目也可以编译过来使用了~

### ISSUE THREAD

**Issue by blilibili** [WeBankFinTech/wxa#88]
wxa是一个挺好用的小程序框架，基本我想要的功能都有，什么函数防抖，节流都不用自己写 从1.0 就开始使用了 写了两，三个项目了 点赞！期望能不能出一个 从原生小程序代码，反向编译到wxa 这样有些老项目也可以使用了~

**Comment by Genuifx** [comment]
新增一个命令 `wxa2 convert` ?

**Comment by blilibili** [comment]
挺好~

**Comment by Genuifx** [comment]
Release at 2.3.1
