### ISSUE TITLE
[feat] 监听 scss 文件的自动刷新

### ISSUE THREAD

**Issue by bestony** [WeBankFinTech/wxa#93]
## Description

出于工程需求，会将 scss 拆分出来进行管理，但在实际的实践过程中发现，如果将 scss 单独拆分出来后，相应修改不会触发自动刷新。

## Environment

  * Platform: 开发者工具
  * Platform version: 1.03.2010240
  * @wxa/cli2 version:2.2.8
  * @wxa/core version: "^2.0.0-alpha.e7e06c46"
  
## Reproduce

将 scss 进行如下拆分

```
.
├── app.wxa
└── scss
    ├── button.scss
    ├── init.scss
    └── variables.scss
```

编辑 scss 文件，不会触发 wxa 的自动构建，样式无法自动应用到版本中。

### Observed Results

  无法完成自动构建
  
### Expected Results

 可以对拆分出的 scss 文件进行自动构建

**Comment by Genuifx** [comment]
这是已经支持的功能，麻烦升级下项目里面的 `@wxa/compiler-sass` 版本
